name: Logger Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"

jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - name: Output Log
        run: echo "main branch pushed"